apiVersion: v1
kind: Pod
metadata:
  name: nginx-deployment
  labels:
        component: web
spec:
  containers: 
    - name: nginxpart2
      image: rajimu/nginx_part_for_k8s
      ports:
        - containerPort: 80