apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      component: web
  template: 
    metadata:
      labels:
        component: web
    spec:
      containers: 
        - name: nginxpart
          image: rajimu/nginx_part_for_k8s
          ports:
            - containerPort: 80